# Generated by Django 4.2.4 on 2023-08-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0008_product_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
