# Generated by Django 4.2.4 on 2023-08-21 17:01

from django.db import migrations, models
import shopapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0011_order_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="preview",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=shopapp.models.product_preview_directory_path,
            ),
        ),
    ]
